### ISSUE TITLE
Error after dump_video_shows

### ISSUE THREAD

**Issue by simonk83** [harryr0se/giant_bomb_cli#5]
It still seems to display all the results (unless there's one at the end causing this) but gives:

```
Traceback (most recent call last):
  File "giant_bomb_cli.py", line 348, in <module>
    main()
  File "giant_bomb_cli.py", line 317, in main
    dump_video_shows(api_key)
  File "giant_bomb_cli.py", line 135, in dump_video_shows
    video_show["title"], video_show["deck"]))
UnicodeEncodeError: 'ascii' codec can't encode character u'\xe9' in position 3: ordinal not in range(128)
```

**Comment by nodakamakadon** [comment]
I see the same output.

**Comment by nodakamakadon** [comment]
Fixed it by slapping this in:

import sys
reload(sys)
sys.setdefaultencoding('UTF8')
